# file: .github/workflows/hello-world.yml
name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  say-hello:
    # операционная система для работы воркфлоу
    runs-on: ubuntu
    steps: # список шагов, которые надо выполнить
      - run: make say-hello
